export const BAD_REQUEST_STATUS_CODE = 400;

export const AUTHENTICATION_ERROR_STATUS_CODE = 403;

export const PERMISSION_ERROR_STATUS_CODE = 401;

export const CONFLICT_ERROR_STATUS_CODE = 409;

export const PRECONDITION_FAILED_STATUS_CODE = 412;
